### ISSUE TITLE
"About" summary is not translatable

### ISSUE THREAD

**Issue by hartenthaler** [JesseWebDotCom/webtrees-theme-modern#10]
At the moment this nice new tab is a mixture of English and German (when using German as webtrees language). Maybe a first step could be to make it consistent in English only. As a second step, it would be nice to make it translatable like the narrative style of JustCarmens custom module [Fancy TreeView](https://github.com/JustCarmen/webtrees-fancy-treeview).

**Comment by JesseWebDotCom** [comment]
let me see if this is something I can do (reminder: I have no idea on how to create a webtrees theme.  I'm just hacking my way through it to create something I and my family would want to use).

**Comment by hartenthaler** [comment]
... ok, but you are really good at doing it that way! Maybe expand your family by adopting some members that are speaking other languages than English ... ;-)

**Comment by JesseWebDotCom** [comment]
Never used Fancy Treeview but just checked it out and it does a similar summary to my "About" tab. I will try to reverse engineer what its doing and incorporate into my theme.

**Comment by JesseWebDotCom** [comment]
And maybe I can turn this into a separate module (and separate it from the theme) - we'll see how it goes

**Comment by hartenthaler** [comment]
> And maybe I can turn this into a separate module (and separate it from the theme)

That is a good idea because this function is a new "tab" and it should not be mixed up with the "theme" function of "modern".

**Comment by JesseWebDotCom** [comment]
Successfully created a separate module for the about tab. Going to take me a while to rewrite - so it includes some fixes as well as language support.

**Comment by JesseWebDotCom** [comment]
This theme has been completely rewritten:
https://github.com/JesseWebDotCom/webtrees-theme-modern/releases/tag/0.0.1

The feature you were using is no longer available in this release. It will return (either in the theme itself or as a separate module) after the theme is stable and I get experience with translation based projects.
