### ISSUE TITLE
Mobile phone

### ISSUE THREAD

**Issue by arbor95** [JesseWebDotCom/webtrees-theme-modern#11]
There are many bugs on a mobile phone.
When will they be solved?

**Comment by JesseWebDotCom** [comment]
Please read the project page - I created this theme for myself and am sharing it with the community with no expectation of support, fixes, etc. if you have specific issues, check open issues and log each one if no one else has reported them. The community may help with potential fixes. I do not intend to try and debug and fix other people’s issues - I’m just trying to get a nice theme for my own personal use.
