### ISSUE TITLE
Error "Call to undefined method" if using the theme "modern" together with the custom Vesta modules

### ISSUE THREAD

**Issue by hartenthaler** [JesseWebDotCom/webtrees-theme-modern#12]
> Call to undefined method Cissee\Webtrees\Module\ExtendedRelationships\ExtendedRelationshipModule::tree() …/modules_v4/webtrees-theme-modern/resources/views/fact.phtml:199
> #0 …/app/View.php(183): include()
> #1 …/app/View.php(278): Fisharebest\Webtrees\View->render()
> #2 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
> #3 …/modules_v4/webtrees-theme-modern/resources/views/modules/personal_facts/tab.phtml(53): view()

**Comment by JesseWebDotCom** [comment]
Good news - this theme has been completely rewritten and your issue has been addressed:
https://github.com/JesseWebDotCom/webtrees-theme-modern/releases/tag/0.0.1
