### ISSUE TITLE
"About" report "married" even if there is no marriage event 

### ISSUE THREAD

**Issue by hartenthaler** [JesseWebDotCom/webtrees-theme-modern#13]
I like this new tab "About".

As far as I have seen:
- it reports "married" even if the partners are not married (if there is no MARR event the standard assumption is that two partners are **not** married)
- it reports occupations and residences only once, even if there are several of those events

**Comment by JesseWebDotCom** [comment]
* fixing married issue
* by design I do not display duplicate named occupations or residences (ex. if you had 3 jobs as a "clerk", the about report will say "worked as a clerk" and not "worked as a clerk, clerk, and clerk"

**Comment by hartenthaler** [comment]
> by design I do not display duplicate named occupations or residences (ex. if you had 3 jobs as a "clerk", the about report will say "worked as a clerk" and not "worked as a clerk, clerk, and clerk"

This is good. But I'm talking about different occupations like "clerk" and "farmer" and residences in different cities.

**Comment by JesseWebDotCom** [comment]
So I don't think its an "only once" thing. I think its because I'm filtering the types of events and you have different types. Here's is how I'm filtering for residences:
```
                    if (in_array($fact->tag(), array('INDI:RESI','INDI:EDUC','INDI:OCCU','INDI:BIRT'))) {
                        $residence = $this->get_state_country($fact->attribute('PLAC'));
```

and here is how I'm filtering for jobs/military:
```
                if ($fact->tag()=='INDI:_MILT') {
                        array_push($services, $fact->value());
                    }
                    if ($fact->tag()=='INDI:OCCU') {
                        array_push($jobs, $fact->value());
                    }
```
Please let me know the tags that I'm missing and I'll add them to the theme.

**Comment by JesseWebDotCom** [comment]
you can also post a sample gedcom and I can figure it out

**Comment by JesseWebDotCom** [comment]
This theme has been completely rewritten:
https://github.com/JesseWebDotCom/webtrees-theme-modern/releases/tag/0.0.1

The feature you were using is no longer available in this release. It will return (either in the theme itself or as a separate module) after the theme is stable and I get experience with translation based projects.
