### ISSUE TITLE
Translation I18N error in resources/views/individual-page.phtml(19)

### ISSUE THREAD

**Issue by hartenthaler** [JesseWebDotCom/webtrees-theme-modern#14]
> 36 arguments are required, 1 given …/app/I18N.php:368
> #0 …/app/I18N.php(368): sprintf()
> #1 …/modules_v4/webtrees-theme-modern/ModernTheme.php(901): Fisharebest\Webtrees\I18N::translate()
> #2 …/modules_v4/webtrees-theme-modern/resources/views/individual-page.phtml(19): JessewebDotCom\Webtrees\Module\ModernTheme\ModernTheme->individual_about()

**Comment by JesseWebDotCom** [comment]
Good news - this theme has been completely rewritten and your issue has been addressed:
https://github.com/JesseWebDotCom/webtrees-theme-modern/releases/tag/0.0.1
