### ISSUE TITLE
Modern Theme : Error

### ISSUE THREAD

**Issue by PeopleSoftBlog** [JesseWebDotCom/webtrees-theme-modern#15]
I like this theme. But Too many issues. I will try to address couple of the things which looks odd. 
1) Paulette folders have brackets and spaces. I believe the space needs to be removed and ( nI eeds to be replaced with -
2) I am using xampp and getting below errors.

ErrorException: filemtime(): stat failed for D:\xampp\htdocs\familytree\modules_v4\webtrees-theme-modern-main/resources/css/palettes/colorful (white-blue-pink)-min.css in D:\xampp\htdocs\familytree\app\Module\ModuleCustomTrait.php:155 Stack trace: #0 [internal function]: Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(2, 'filemtime(): st...', 'D:\\xampp\\htdocs...', 155) #1 D:\xampp\htdocs\familytree\app\Module\ModuleCustomTrait.php(155): filemtime('D:\\xampp\\htdocs...') #2 D:\xampp\htdocs\familytree\modules_v4\webtrees-theme-modern-main\ModernTheme.php(305): JessewebDotCom\Webtrees\Module\ModernTheme\ModernTheme->assetUrl('css/palettes/co...') #3 D:\xampp\htdocs\familytree\modules_v4\webtrees-theme-modern-main\resources\views\layouts\default.phtml(64): JessewebDotCom\Webtrees\Module\ModernTheme\ModernTheme->stylesheets() #4 D:\xampp\htdocs\familytree\app\View.php(183): include('D:\\xampp\\htdocs...') #5 D:\xampp\htdocs\familytree\app\View.php(278): Fisharebest\Webtrees\View->render() #6 D:\xampp\htdocs\familytree\app\Helpers\functions.php(145): Fisharebest\Webtrees\View::make('layouts/default', Array) #7 D:\xampp\htdocs\familytree\app\Http\ViewResponseTrait.php(54): view('layouts/default', Array) #8 D:\xampp\htdocs\familytree\app\Http\RequestHandlers\UserPage.php(80): Fisharebest\Webtrees\Http\RequestHandlers\UserPage->viewResponse('user-page', Array) #9 D:\xampp\htdocs\familytree\app\Http\Middleware\RequestHandler.php(55): Fisharebest\Webtrees\Http\RequestHandlers\UserPage->handle(Object(Nyholm\Psr7\ServerRequest)) #10 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #11 D:\xampp\htdocs\familytree\modules_v4\vesta_research_suggestions\ResearchSuggestionsModule.php(277): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #12 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(136): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #13 D:\xampp\htdocs\familytree\app\Module\HitCountFooterModule.php(154): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #14 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #15 D:\xampp\htdocs\familytree\app\Module\CheckForNewVersion.php(122): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #16 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #17 D:\xampp\htdocs\familytree\app\Http\Middleware\AuthLoggedIn.php(51): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #18 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\AuthLoggedIn->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #19 D:\xampp\htdocs\familytree\app\Http\Middleware\CheckCsrf.php(80): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #20 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #21 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #22 D:\xampp\htdocs\familytree\app\Webtrees.php(275): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest)) #23 D:\xampp\htdocs\familytree\app\Http\Middleware\Router.php(161): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array) #24 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #25 D:\xampp\htdocs\familytree\app\Http\Middleware\BootModules.php(60): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #26 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #27 D:\xampp\htdocs\familytree\app\Http\Middleware\RegisterGedcomTags.php(54): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #28 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #29 D:\xampp\htdocs\familytree\app\Http\Middleware\LoadRoutes.php(75): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #30 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #31 D:\xampp\htdocs\familytree\app\Http\Middleware\CheckForNewVersion.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #32 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #33 D:\xampp\htdocs\familytree\app\Http\Middleware\UseTransaction.php(45): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #34 D:\xampp\htdocs\familytree\vendor\illuminate\database\Concerns\ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection)) #35 D:\xampp\htdocs\familytree\app\Http\Middleware\UseTransaction.php(44): Illuminate\Database\Connection->transaction(Object(Closure), 3) #36 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #37 D:\xampp\htdocs\familytree\app\Http\Middleware\DoHousekeeping.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #38 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #39 D:\xampp\htdocs\familytree\app\Http\Middleware\UseTheme.php(69): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #40 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #41 D:\xampp\htdocs\familytree\app\Http\Middleware\CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #42 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #43 D:\xampp\htdocs\familytree\app\Http\Middleware\UseLanguage.php(71): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #44 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #45 D:\xampp\htdocs\familytree\app\Http\Middleware\UseSession.php(78): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #46 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #47 D:\xampp\htdocs\familytree\app\Http\Middleware\UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #48 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #49 D:\xampp\htdocs\familytree\app\Http\Middleware\UseDatabase.php(122): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #50 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #51 D:\xampp\htdocs\familytree\app\Http\Middleware\BadBotBlocker.php(282): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #52 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #53 D:\xampp\htdocs\familytree\app\Http\Middleware\CompressResponse.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #54 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #55 D:\xampp\htdocs\familytree\app\Http\Middleware\ContentLength.php(40): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #56 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #57 D:\xampp\htdocs\familytree\vendor\middlewares\client-ip\src\ClientIp.php(65): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #58 D:\xampp\htdocs\familytree\app\Http\Middleware\ClientIp.php(47): Middlewares\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #59 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #60 D:\xampp\htdocs\familytree\app\Http\Middleware\HandleExceptions.php(90): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #61 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #62 D:\xampp\htdocs\familytree\app\Http\Middleware\BaseUrl.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #63 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #64 D:\xampp\htdocs\familytree\app\Http\Middleware\ReadConfigIni.php(68): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #65 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #66 D:\xampp\htdocs\familytree\app\Http\Middleware\SecurityHeaders.php(48): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #67 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #68 D:\xampp\htdocs\familytree\app\Http\Middleware\EmitResponse.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #69 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #70 D:\xampp\htdocs\familytree\vendor\oscarotero\middleland\src\Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #71 D:\xampp\htdocs\familytree\app\Webtrees.php(275): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest)) #72 D:\xampp\htdocs\familytree\app\Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array) #73 D:\xampp\htdocs\familytree\index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest() #74 {main}

**Comment by JesseWebDotCom** [comment]
Good news - this theme has been completely rewritten and your issue has been addressed:
https://github.com/JesseWebDotCom/webtrees-theme-modern/releases/tag/0.0.1
