### ISSUE TITLE
Readfile of URL not possible in general

### ISSUE THREAD

**Issue by tvogel** [JesseWebDotCom/webtrees-theme-modern#16]
My hoster does not allow retrieving data from the public URI using `readfile()`. They reply with 401 in this case. Therefore, the current approach to join the stylesheets does not work here:

https://github.com/JesseWebDotCom/webtrees-theme-modern/blob/091dbf45c9dbe85d8ca5ae6a5fb0731c9e90cd8e/resources/views/layouts/default.phtml#L65

I locally tried adding methods to the module to retrieve the paths for the stylesheets only and use those in `readfile()` which works. However, I ran into other (unrelated) problems, so cannot easily make a PR but still wanted to make you aware.

**Comment by JesseWebDotCom** [comment]
Good news - this theme has been completely rewritten and your issue has been addressed:
https://github.com/JesseWebDotCom/webtrees-theme-modern/releases/tag/0.0.1
