### ISSUE TITLE
Running I18N::translate() on already composed string does not work

### ISSUE THREAD

**Issue by tvogel** [JesseWebDotCom/webtrees-theme-modern#17]
The code for translating the about string does not work as intended:

https://github.com/JesseWebDotCom/webtrees-theme-modern/blob/091dbf45c9dbe85d8ca5ae6a5fb0731c9e90cd8e/ModernTheme.php#L901

If this should work, the whole, composed string would need a corresponding entry in the translation database which of course does not make sense. So, instead, you'll need to translate the individual phrases before concatenating them.

Also, because the composed string contains links including "%" signs, `I18N::translate()` will justifiably complain about variables missing for these which are mistaken as `sprintf`-placeholders.

**Comment by JesseWebDotCom** [comment]
This theme has been completely rewritten:
https://github.com/JesseWebDotCom/webtrees-theme-modern/releases/tag/0.0.1

The feature you were using is no longer available in this release. It will return (either in the theme itself or as a separate module) after the theme is stable and I get experience with translation based projects.
