### ISSUE TITLE
Page header covers contents of page

### ISSUE THREAD

**Issue by ekdahl** [JesseWebDotCom/webtrees-theme-modern#19]
When top part of the page with the menu gets higher, the part of the page with the contents doesn't follow. So when there is a high header the top of the contents can't be seen because it it behind the header. This is more visible for some of the palettes.

Sample image below with modern-default palette and the window width that produces the highest header.
![image](https://github.com/JesseWebDotCom/webtrees-theme-modern/assets/2682230/712f8d8b-23d1-4862-a6ab-f5440b8e763e)

**Comment by hartenthaler** [comment]
Yes, I can see this, too. And if there is a FancyImageBar this is invisible now.

**Comment by JesseWebDotCom** [comment]
Release 0.0.2 should fix this issue: https://github.com/JesseWebDotCom/webtrees-theme-modern/releases/tag/0.0.2

**Comment by JesseWebDotCom** [comment]
Fixed - also verified compatibility with fancyimagebar
