### ISSUE TITLE
Background with darkly palette is still light

### ISSUE THREAD

**Issue by ekdahl** [JesseWebDotCom/webtrees-theme-modern#20]
The background of the content part of the page is still light when selecting the darkly palette, which renders the page header unreadable.
![image](https://github.com/JesseWebDotCom/webtrees-theme-modern/assets/2682230/c3077ce9-4180-4565-bb6f-5275536bc771)

**Comment by JesseWebDotCom** [comment]
Fixed - https://github.com/JesseWebDotCom/webtrees-theme-modern/releases/tag/0.0.3
