### ISSUE TITLE
Wrong colors in menu for bootswatch palettes?

### ISSUE THREAD

**Issue by ekdahl** [JesseWebDotCom/webtrees-theme-modern#21]
See screenshot with side by side comparison between webtrees with darkly palette vs bootswatch sample page with darkly. Should the webtrees top menu also be blue with with white text here? 
![image](https://github.com/JesseWebDotCom/webtrees-theme-modern/assets/2682230/e1ed5204-ae80-41c6-acc0-0b6fd1cdb30c)

**Comment by JesseWebDotCom** [comment]
I don’t plan to have the themes align perfectly to bootwatch. Feel free to mess around with the css files - if you figure out the alignment, you can respond back and I’ll update the core files.

**Comment by JesseWebDotCom** [comment]
Closing - theme does align to darkly colors (dark gray)
