### ISSUE TITLE
More Icons

### ISSUE THREAD

**Issue by hartenthaler** [JesseWebDotCom/webtrees-theme-modern#24]
Maybe you can add icons for the standard webtrees menu topics
- stories
- FAQ

How can I add custom icons for
- Familienbericht (JustCarmen's Fancy TreeView)
- Handbuch (manual)

![IMG_3308](https://github.com/JesseWebDotCom/webtrees-theme-modern/assets/6324175/ef70dc42-407a-4f65-bb57-f7352a22a1c9)

**Comment by JesseWebDotCom** [comment]
This is partially addressed in release 0.0.5:
https://github.com/JesseWebDotCom/webtrees-theme-modern/releases/tag/0.0.5

I can't figure out how to add Stories and Fancy Treeview to the menus.

**Comment by hartenthaler** [comment]
Stories: Control panel / All modules / Tabs: then activate "Stories" for your tree
[Fancy Treeview](https://github.com/JustCarmen/webtrees-fancy-treeview) is a custom module with some similarity to your module webtrees-tab-lifestory

Thank you, for all the enhancements!

**Comment by JesseWebDotCom** [comment]
I have both enabled but those items are tab items, not menu items

**Comment by JesseWebDotCom** [comment]
Closing as all icons that can be added were added
