### ISSUE TITLE
Location tab text overlays other text on iPhone

### ISSUE THREAD

**Issue by hartenthaler** [JesseWebDotCom/webtrees-theme-modern#25]
When using the bootswatch-darkly palette on an iPhone and showing the locations tab then the text of that tab overlays already existing text.

![IMG_3307](https://github.com/JesseWebDotCom/webtrees-theme-modern/assets/6324175/e5e06ba1-e344-4290-a5f4-b4f0d1a07dcb)

**Comment by JesseWebDotCom** [comment]
This is partially fixed in release 0.0.5:
https://github.com/JesseWebDotCom/webtrees-theme-modern/releases/tag/0.0.5

I can't figure out how to make the footer stay at the bottom of the page

**Comment by JesseWebDotCom** [comment]
Can you reply with a screenshot of the same URL but with the webtrees theme?  I suspect this is a webtrees issue.

**Comment by hartenthaler** [comment]
Oh, yes. In the webtrees theme, there is the same problem. On the iPhone, the legend of the "places" tab is in the background and only the first line is visible. This is now - after your last change - the same behaviour in the modern theme. So finally this is now a general webtrees issue.

**Comment by JesseWebDotCom** [comment]
Awesome. I’m going to close this.  Can you put an issue in the webtrees GitHub?  Thanks
