### ISSUE TITLE
Image is disturbing the block "slide show" at tree home page

### ISSUE THREAD

**Issue by hartenthaler** [JesseWebDotCom/webtrees-theme-modern#28]
There is an additional image in front of the name in the block "Slide show". This image should be removed (because it is in most cases identical to the shown image in the slide show) or should be reduced in size (because it hides the first name of the person). 

![Screenshot (9)](https://github.com/JesseWebDotCom/webtrees-theme-modern/assets/6324175/a7afaafd-8084-4879-a3bf-61d1b82a0f31)

**Comment by JesseWebDotCom** [comment]
try the latest release: https://github.com/JesseWebDotCom/webtrees-theme-modern/releases/tag/0.0.8

**Comment by JesseWebDotCom** [comment]
closing, fixed starting with release 0.0.8

**Comment by hartenthaler** [comment]
Sorry, but it is not fixed for me, even in 0.1.0. The image is still too large and outside of the box (using Chrome and Edge).
![Screenshot (362)](https://github.com/JesseWebDotCom/webtrees-theme-modern/assets/6324175/7b2625f9-d949-4d4b-9e40-12a292725650)

**Comment by JesseWebDotCom** [comment]
and what about the default theme?

**Comment by JesseWebDotCom** [comment]
Here's chrome and safari on Mac - both with the ancestry palette you are using.  Also displays fine on mobile safari. maybe you have some odd caching or browser thing happening.

<img width="443" alt="Screenshot 2023-07-07 at 2 03 15 PM" src="https://github.com/JesseWebDotCom/webtrees-theme-modern/assets/20848952/94c03992-266d-4167-8453-d015e09a58f1">
![Screenshot 2023-07-07 at 2 02 34 PM](https://github.com/JesseWebDotCom/webtrees-theme-modern/assets/20848952/b42f3261-6afc-492a-a98f-63eb23894a98)

**Comment by hartenthaler** [comment]
Ah! In "modern-default" it is very small, centered and ok!

**Comment by JesseWebDotCom** [comment]
> Ah! In "modern-default" it is very small, centered and ok!

I'll bring this change to all palettes in the next release and then you can see if it fixes the issue for you.

**Comment by hartenthaler** [comment]
I'm using Chrome and Edge on a Windows PC. Only in the modern-default it is ok. 

When using Edge on the iPhone is ok for modern-default, but not ok for all the other palettes.

**Comment by JesseWebDotCom** [comment]
Got it. Can you also see my comment on issue #28? I wan you to tell me (and screenshot) if the same problem happens using the webtrees theme.

**Comment by hartenthaler** [comment]
> inspect the thumbnail and see what the value is for .wt-chart-box-thumbnail. it should be this as set by the theme:

Sorry! My fault! I had forgotten that I made a change a year ago to the size of the thumbnail in the CSS&JS module that interfered now with your module. I removed that,  and now it looks great! Sorry.

**Comment by JesseWebDotCom** [comment]
Fixed (across all themes): https://github.com/JesseWebDotCom/webtrees-theme-modern/releases/tag/0.1.1
