### ISSUE TITLE
Interactive tree shown incorrect

### ISSUE THREAD

**Issue by arbor95** [JesseWebDotCom/webtrees-theme-modern#3]
The interactive tree (das interaktive Sanduhr Diagramm)  is shown incorrect (fehlende Icons und geschachtelte Boxen).

**Comment by hartenthaler** [comment]
![Screenshot (169)](https://user-images.githubusercontent.com/6324175/218715535-954a4f4d-0d8a-4cd9-9e2a-9c53460ace64.png)

This issue is still open when using V2.1.16.1 of this theme.

**Comment by JesseWebDotCom** [comment]
Good news - this theme has been completely rewritten and your issue has been addressed:
https://github.com/JesseWebDotCom/webtrees-theme-modern/releases/tag/0.0.1
