### ISSUE TITLE
Cloudflare

### ISSUE THREAD

**Issue by hartenthaler** [JesseWebDotCom/webtrees-theme-modern#33]
I have a question: I observed several times in the status line of the browser a message "TLS Handshake cdnjs.cloudflare.com". I had never seen this before. Was this introduced by the "modern" theme?

Maybe another question is related to that topic: based on European data security laws, it is not allowed to transfer data like IP addresses form Europe to the USA without informing and/or asking the user for permission. So I installed necessary Google fonts locally instead of loading them dynamically from a Google server in the USA. Your "modern" theme is using many nice fonts. Are they loaded dynamically?

**Comment by JesseWebDotCom** [comment]
Fixed: https://github.com/JesseWebDotCom/webtrees-theme-modern/releases/tag/0.1.1

boostrap file is locally pulled instead of cdn
I don't have any other cdn references - everything should be served from the local server
