### ISSUE TITLE
Languages mixed up

### ISSUE THREAD

**Issue by hartenthaler** [JesseWebDotCom/webtrees-theme-modern#37]
I'm using "German" as the language, but in the main menu and in the control panel the entries of the modern theme are now in Dutch.

"HOOFDMENU" instead of "HAUPTMENÜ"
![Screenshot (368)](https://github.com/JesseWebDotCom/webtrees-theme-modern/assets/6324175/f7c89376-377d-4cb4-a9f8-8501e918c691)

**Comment by JesseWebDotCom** [comment]
Is this fixed for you in the latest version?

**Comment by hartenthaler** [comment]
Yes, this is solved in 0.1.1. Thank you!
