### ISSUE TITLE
Search in main menu does not work

### ISSUE THREAD

**Issue by hartenthaler** [JesseWebDotCom/webtrees-theme-modern#38]
When using the main menu search function, there are no results and the tree is changed to the default tree of the website.

![Screenshot (371)](https://github.com/JesseWebDotCom/webtrees-theme-modern/assets/6324175/5a1d4a09-d1b8-4da7-9698-d68e47bf6f74)

**Comment by JesseWebDotCom** [comment]
Fixed: https://github.com/JesseWebDotCom/webtrees-theme-modern/releases/tag/0.1.1
