### ISSUE TITLE
Error: failed to open stream: HTTP request failed! ... in C:\wamp\www\webtrees217\[...]\default.phtml:61

### ISSUE THREAD

**Issue by Shaashimov** [JesseWebDotCom/webtrees-theme-modern#4]
Hello.
I kep having an error when choissing this theme.
It seems like getting css files is not possible. The error lines is copuied below ↓

`<?php // combine all CSS files so they can share variables
        echo('<style type="text/css">');
        foreach (app(ModuleThemeInterface::class)->stylesheets() as $stylesheet) {
            readfile(e($stylesheet));
        } 
        echo('</style>');
?>`

Other themes seems to work. 
Do you have a solution in mind?
Thank you

**Comment by hartenthaler** [comment]
duplicated issue, see #1

**Comment by JesseWebDotCom** [comment]
see if this new release fixes the issue: https://github.com/JesseWebDotCom/webtrees-theme-modern/releases/tag/v2.1.16.1

**Comment by JesseWebDotCom** [comment]
Good news - this theme has been completely rewritten and your issue has been addressed:
https://github.com/JesseWebDotCom/webtrees-theme-modern/releases/tag/0.0.1
