### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by hartenthaler** [JesseWebDotCom/webtrees-theme-modern#5]
In your nice theme there is in the footer a copyright claim:
`[© 2022 jesseweb.com](https://jesseweb.com/)`

This is ok for your design, but I don't like to give you the copyright for my webtrees site. Please remove this claim. Maybe you can add something like "Designed by ..." (see theme JustLight).

**Comment by JesseWebDotCom** [comment]
Fixed in upcoming release - you can control the text, the url, and if you want to display a copyright at all
