### ISSUE TITLE
Imprint footer element does not work with this theme

### ISSUE THREAD

**Issue by hartenthaler** [JesseWebDotCom/webtrees-theme-modern#6]
I have developed a custom footer module: https://github.com/hartenthaler/hh_imprint

This adds a new element to the footer. It is working in all themes, but when using the theme "modern" it is not visible.

**Comment by JesseWebDotCom** [comment]
Good news - this theme has been completely rewritten and your issue has been addressed:
https://github.com/JesseWebDotCom/webtrees-theme-modern/releases/tag/0.0.1
