### ISSUE TITLE
Incompatible with Vesta custom modules

### ISSUE THREAD

**Issue by hartenthaler** [JesseWebDotCom/webtrees-theme-modern#7]
When using the [Vesta modules](https://github.com/vesta-webtrees-2-custom-modules/vesta_personal_facts) the tab "facts and events" of the Vesta modules is empty.

**Comment by JesseWebDotCom** [comment]
Good news - this theme has been completely rewritten and your issue has been addressed:
https://github.com/JesseWebDotCom/webtrees-theme-modern/releases/tag/0.0.1
