### ISSUE TITLE
In "settings" Copyright name and URL is necessary even if this option is disabled

### ISSUE THREAD

**Issue by hartenthaler** [JesseWebDotCom/webtrees-theme-modern#8]
When disabling this option it should not be necessary to specify the name and URL for copyright.

**Comment by JesseWebDotCom** [comment]
I don't know how to do that. Can you point me to an existing webtrees module that has a settings page where unchecking of an option displays/hides other options.

**Comment by hartenthaler** [comment]
Oh, no it is not about hiding. It is about that you check if there is content in Copyright Name and URL. It makes no sense to deselect the copyright option and nevertheless have to put content to those fields.

**Comment by JesseWebDotCom** [comment]
Good news - this theme has been completely rewritten and your issue has been addressed:
https://github.com/JesseWebDotCom/webtrees-theme-modern/releases/tag/0.0.1
