### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by hartenthaler** [JesseWebDotCom/webtrees-theme-modern#9]
I like to translate your module into German. What do you prefer?
- poeditor.com (my preference)
- po/mo files
- PHP file

**Comment by JesseWebDotCom** [comment]
I will checkout poeditor.com

**Comment by hartenthaler** [comment]
It is used by several custom webtrees modules (like Fancy Tree View and GVExport). You can link it to GitHub.

**Comment by JesseWebDotCom** [comment]
Yeo - I'm looking at the fancy treeview source code and poeditor.com project to see how to do it. Once I figure it out, I'll make the poeditor project public to allow others like yourself to translate.

**Comment by JesseWebDotCom** [comment]
Do you have to pay for poeditor? Otherwise I'll just create the po files myself

**Comment by hartenthaler** [comment]
No, it is free. At least r here is a free option.

**Comment by JesseWebDotCom** [comment]
This theme has been completely rewritten:
https://github.com/JesseWebDotCom/webtrees-theme-modern/releases/tag/0.0.1

The feature you were using is no longer available in this release. It will return (either in the theme itself or as a separate module) after the theme is stable and I get experience with translation based projects.
